// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLAnbFTM42M5A7PdFjnlBIzOVEHa6s118',
    appId: '1:685574440358:web:a331ba9258e7f5a9987b67',
    messagingSenderId: '685574440358',
    projectId: 'complete-will-240606',
    authDomain: 'complete-will-240606.firebaseapp.com',
    databaseURL: 'https://complete-will-240606.firebaseio.com',
    storageBucket: 'complete-will-240606.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwCmaVHrjzCX-629bFznh2CviFm3hQ5NA',
    appId: '1:685574440358:android:78011d3885c31408987b67',
    messagingSenderId: '685574440358',
    projectId: 'complete-will-240606',
    databaseURL: 'https://complete-will-240606.firebaseio.com',
    storageBucket: 'complete-will-240606.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsXJQFBRGjVtS6KhzGynoE7LnXh78rHBI',
    appId: '1:685574440358:ios:d907f8f8be8557b0987b67',
    messagingSenderId: '685574440358',
    projectId: 'complete-will-240606',
    databaseURL: 'https://complete-will-240606.firebaseio.com',
    storageBucket: 'complete-will-240606.firebasestorage.app',
    iosClientId: '685574440358-8ar694nfmopno1drlkl941h8837oaq4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsXJQFBRGjVtS6KhzGynoE7LnXh78rHBI',
    appId: '1:685574440358:ios:d907f8f8be8557b0987b67',
    messagingSenderId: '685574440358',
    projectId: 'complete-will-240606',
    databaseURL: 'https://complete-will-240606.firebaseio.com',
    storageBucket: 'complete-will-240606.firebasestorage.app',
    iosClientId: '685574440358-8ar694nfmopno1drlkl941h8837oaq4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLAnbFTM42M5A7PdFjnlBIzOVEHa6s118',
    appId: '1:685574440358:web:fe392857c0d036a3987b67',
    messagingSenderId: '685574440358',
    projectId: 'complete-will-240606',
    authDomain: 'complete-will-240606.firebaseapp.com',
    databaseURL: 'https://complete-will-240606.firebaseio.com',
    storageBucket: 'complete-will-240606.firebasestorage.app',
  );

}